const types = {
  INCREMENT_COUNTER : 'INCREMENT_COUNTER',
  FETCH_PLACES_REQUEST : 'FETCH_PLACES_REQUEST',
  FETCH_PLACES_SUCCESS : 'FETCH_PLACES_SUCCESS',
  FETCH_PLACES_ERROR : 'FETCH_PLACES_ERROR',
  ADD_PLACE : 'ADD_PLACE',
  TOGGLE_PLACE : 'TOGGLE_PLACE',
};

export default types;